version: "3"
services:
  app:
    build: .
    tty: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/bakery
  db:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=bakery
